CREATE TABLE autor (
	codigo BIGINT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	sexo VARCHAR(12),
	email VARCHAR(100),
	data_nascimento VARCHAR(12),
	nacionalidade VARCHAR(50),
	cpf VARCHAR(14)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
